### ISSUE TITLE
Can't install limbic using pip

### ISSUE THREAD

**Issue by ArjunSarihyan** [glhuilli/limbic#7]
**The Error code is as follows**
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-x99amdpm\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-x99amdpm\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ARJUNS~1\AppData\Local\Temp\pip-record-rvpycn84\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python37\Include\cytoolz'
         cwd: C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-x99amdpm\cytoolz\
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.7\cytoolz
    creating build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.7\cytoolz
    creating build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.7\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-x99amdpm\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-x99amdpm\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ARJUNS~1\AppData\Local\Temp\pip-record-rvpycn84\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python37\Include\cytoolz' Check the logs for full command output.

**Comment by ArjunSarihyan** [comment]
Additionally my python version is 3.7.4

**Comment by glhuilli** [comment]
@ArjunSarihyan were you able to install `Microsoft Visual C++ 14.0`?

**Comment by glhuilli** [comment]
Closing this ticket after a year of inactivity.
